import { Role } from "@prisma/client"

export type Permission =
    | "VIEW_DASHBOARD"
    | "VIEW_SCOUTS"
    | "VIEW_TRANSACTIONS"
    | "VIEW_CAMPOUTS"
    | "VIEW_REPORTS"
    | "VIEW_USERS"
    | "VIEW_SETTINGS"
    | "MANAGE_SCOUTS"
    | "MANAGE_FINANCE"
    | "MANAGE_USERS"
    | "VIEW_FUNDRAISING"
    | "MANAGE_FUNDRAISING"
    | "VIEW_BILLING"

// Default permissions if none are set in DB
export const DEFAULT_PERMISSIONS: Record<Role, Permission[]> = {
    ADMIN: [
        "VIEW_DASHBOARD", "VIEW_SCOUTS", "VIEW_TRANSACTIONS", "VIEW_CAMPOUTS", "VIEW_REPORTS", "VIEW_USERS", "VIEW_SETTINGS",
        "MANAGE_SCOUTS", "MANAGE_FINANCE", "MANAGE_USERS", "VIEW_FUNDRAISING", "MANAGE_FUNDRAISING", "VIEW_BILLING"
    ],
    FINANCIER: [
        "VIEW_DASHBOARD", "VIEW_SCOUTS", "VIEW_TRANSACTIONS", "VIEW_CAMPOUTS", "VIEW_REPORTS", "VIEW_SETTINGS",
        "MANAGE_FINANCE", "MANAGE_SCOUTS", "VIEW_FUNDRAISING", "MANAGE_FUNDRAISING", "VIEW_BILLING"
    ],
    LEADER: [
        "VIEW_DASHBOARD", "VIEW_SCOUTS", "VIEW_CAMPOUTS", "VIEW_REPORTS", "VIEW_TRANSACTIONS", "VIEW_SETTINGS",
        "MANAGE_SCOUTS", "VIEW_FUNDRAISING", "MANAGE_FUNDRAISING"
    ],
    PARENT: [
        "VIEW_DASHBOARD", "VIEW_SCOUTS", "VIEW_CAMPOUTS", "VIEW_SETTINGS",
        "MANAGE_SCOUTS", "VIEW_FUNDRAISING"
    ],
    SCOUT: [
        "VIEW_DASHBOARD", "VIEW_CAMPOUTS", "VIEW_TRANSACTIONS", "VIEW_SCOUTS", "VIEW_FUNDRAISING", "VIEW_SETTINGS"
    ],
    PLATFORM_ADMIN: [
        "VIEW_DASHBOARD", "VIEW_SCOUTS", "VIEW_TRANSACTIONS", "VIEW_CAMPOUTS", "VIEW_REPORTS", "VIEW_USERS", "VIEW_SETTINGS",
        "MANAGE_SCOUTS", "MANAGE_FINANCE", "MANAGE_USERS", "VIEW_FUNDRAISING", "MANAGE_FUNDRAISING", "VIEW_BILLING"
    ]
}
